version: '3'

vars:
  BIN: bkptool
  BIN_DIR: ./bin

silent: false

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build bkptool binary into ./bin
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/{{.BIN}} ./cmd

  run:
    desc: Run bkptool from source
    cmds:
      - go run ./cmd -- {{.CLI_ARGS}}

  test:
    desc: Run unit tests
    cmds:
      - go test ./...
